// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByyBM1VN5sqsoAVQIieewEKFQEV0FRj9s',
    appId: '1:1057633659352:android:a118154bc006217907eaad',
    messagingSenderId: '1057633659352',
    projectId: 'yongjun-learn-flutter-project1',
    storageBucket: 'yongjun-learn-flutter-project1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlMcK17LqQVo8G0wYh-OBkSteguM4nUac',
    appId: '1:1057633659352:ios:2fd5e917cf54984907eaad',
    messagingSenderId: '1057633659352',
    projectId: 'yongjun-learn-flutter-project1',
    storageBucket: 'yongjun-learn-flutter-project1.appspot.com',
    iosClientId: '1057633659352-fveqqhdancq1e21eleo8kvrq9pbgsd1n.apps.googleusercontent.com',
    iosBundleId: 'com.yongjun1998.mypersonalnotes',
  );
}
